name: Test with Python 3.8

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install httpx git+https://github.com/pytube/pytube
    - name: Sync
      run: python syncExample.py
    - name: Async
      run: python asyncExample.py
      
  armv64_job:
      name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
      runs-on: ubuntu-20.04
      strategy:
        fail-fast: false
        matrix:
          python-version:
            - 3.8
          
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt update && \
              apt install -y python3.8 && \
              apt install -y python3.8-venv && \
              python3.8 -m venv .env && \
              source .env/bin/activate && \
              python -m pip install --upgrade pip && \
              python -m pip install httpx git+https://github.com/pytube/pytube && \
              python syncExample.py && \
              python asyncExample.py && \
              deactivate'     
